CREATE TABLE [dbo].[Orders]
(
	[Id]			INT	IDENTITY(1,1)		NOT NULL	CONSTRAINT PK_Orders			PRIMARY KEY				CLUSTERED,
	[ItemId]		INT						NOT NULL	CONSTRAINT FK_Orders_ItemId		REFERENCES Items(Id)	ON UPDATE CASCADE ON DELETE CASCADE,
	[Quantity]		TINYINT	DEFAULT(0)		NOT NULL,
	[TotalPrice]	DECIMAL(7,2)			NOT NULL,
	[Status]		NVARCHAR(10)			NOT NULL,
	[CreatedBy]		NVARCHAR(255)			NOT NULL,
	[CreatedOn]		DATETIME2				NOT NULL
)
